### ISSUE TITLE
Platform not found: 'sensor.ping'

### ISSUE THREAD

**Issue by benjaminvdb** [trombik/esphome-component-ping#23]
I think the latest version of ESPHome (2022.3.0) introduced a [breaking change](https://github.com/esphome/esphome/pull/3216) that may have affected this project. The signature of the `sensor.sensor_schema()` method has changed and we probably need to pass in keyword instead of positional arguments to this method [here](https://github.com/esphome/esphome/blob/a8100f103d7c36c1ab4af5c2a0dbac67fa7ca562/esphome/components/bl0940/sensor.py#L35-L40).

```
INFO Reading configuration /config/esphome/kookeiland.yaml...
ERROR Unable to load component ping.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/43f13ef2/components/ping/sensor.py", line 59, in <module>
    cv.Optional(CONF_LOSS): sensor.sensor_schema(
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 5 were given
Failed config

sensor.ping: [source /config/esphome/kookeiland.yaml:142]
  
  Platform not found: 'sensor.ping'.
```

**Comment by trombik** [comment]
would you test your device with this branch?

https://github.com/trombik/esphome-component-ping/tree/issue_23
